package com.everybodycodes2025.solver;

import java.util.Arrays;
import java.util.stream.Collectors;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Day06 implements Puzzle {

  private static final Logger LOGGER = LoggerFactory.getLogger(Day06.class);

  // private static final String FILE_NAME = "day06.txt";

  @Override
  public void solve() {
    LOGGER.debug("part1: {}", calculatePart1NoviceMentorPairByChar(
        "ABCaCcAbaACbCBcbBACbcBcaBCCabbcCCaAcACAAaCbaAbcCCaBbABbbcAAABCAAcaaBabbabbBbbBabBBCaCCAbbbaAbbACAbBB",
        'a'));

    int part2Sum = 0;
    for (char c : Arrays.asList('a', 'b', 'c')) {
      part2Sum += calculatePart1NoviceMentorPairByChar(
          "ABCcbbAbbACcBAacbacBBaabBCcbCaAaacCBbACBaccAccBABcCaaAAAAbabCbaCaccABBBBbAAcbbabcBbCCBbBaCbacabaBaAAbcccCBcBbBbcAaCCBaBCBCbBaCBbCCBCbCcccaAcCCabAbcaACcaBCcaACcAbAAAcCaAabCaCBAABbbCCBBAaabACCabbAABbBBACBAACBcbAcCaBBAcAaCccCaaCaAccAaaaBaACcBcCaaAbcCBbBAaaCAcbAcCAccCBaAAbbBcBbBaBACcbCAabaACBacCcbBCbABb",
          c);
      // LOGGER.debug("part2 test: {}", part2Sum);
    }
    LOGGER.debug("part2: {}", part2Sum);

    int range = 1000;
    int repeat = 1000;
    var part3Notes =
        "acABacccaAacCacaCBCcABAccaBBccaAcccAAcbCCcccbcaBcabaAbAcbbACaACBabCBBccbaBcaBcAacABCCabBBCbCaBCcbAabBBcAaCbaBacCabccBCCbbcCacABBbCaCBBBAAbcAbbAbAbbaCbcAcBacCbabACCBaBAaaBAbcaaaCbBCABBccCacaabCaAccBccCAcBcBBBaCCcCcAaaaCcbCAAAAcacacCacaCCaAcBCbcCcBAcbCcaAbaAcAbCCaBACAbCabaBBBaBABBaAaAaaBBabCCAbbcBbCcaCaCBCcCaabCCaccCAABabAAacBaAACbCCCAaCcBaBbcAcBaCCcBAcCaBCCAAABACcbcbbccccbCACaBCCACabAabbBBCcCbbCBACaccBabaBBcCCBaAabaCCAabBbBcCcBbcCaccaaAcAAacCAbbCcaAcBbbCAcbCacAaCBAcacbAabBcCbCbcBcAbaAAAaaaccBabcbcacAcBbAAbbcbAaBCCCaCbaAaaBBaCaBcCbAccABabABbbcACACabaBCcacbaCcAACbCAaAACbaaaAACBBccbAcCABAAcABBbaacBBCbBaaABAACbbAabAbbCbbAACabaabaAbbaCbBCCbccABcaACAAAABBcbBabaCbbCcBcBCAccAAccBaCbBBCbbCBBcCCabcBbBcAbbabACaaccaCCaabcacBaCbAcbACcbacAbACBbCBBcBAcAAcBAAcbCcCCbCBBabAaCACCCcAacCbAAaBcbACaCabbabaACAAcaCabAAAcABcAAbbCBccCBCbCACBbaACaaaCAbBaacbBAbCbACbBCCCbBbAAcbcaaBaCcCAAabbccCbbBaABcCCBbBCCAcAcBBABbAbbbBabBbAaBCBCAabBACbABBbBCcaccacCBCBAbCcccCCBaaBbABccCBcaaCBbbcACaCccBbCCBcbBaAAbbbbaABaaAACBAaCaCCBBbCccaAAcACACcaCbCbaBCbaABBbCbbACccaBBaAcbAaAbCcBacacBabbCBBCccccAAbCaCaCBBBacbbabCbbaABbcAcBcbCbCABbccAABACcaccbCaBacccBCABBAbcbCCcCABaBBBACaaCAACacAbBCaAaCBACCccBAbaBCaCaBACBCcacabcaBBcAbaaCBbcBaCCbCCAbABCaCAACCcCBabcCaAaccCacCCACCAAbBbCbcAbbabbbacCBaaBCcccbBcbccAbABabBAacACAACBCBaBCBaBBBbbBAAAaBaBaBaCcccbAbaABCcbaCBCacccBCcaBbcAcCBAccBBbAaacbcBcccccbcaaabcAAbAcBbCCCAbBaACCAcCbBcaCaBBaACbbacaCAaaAAcBbCaaBAAbcaCCaAbCcCbcacbCbABAaacacCCccBCaabbcbBCcCAAbCCCBAABbCAaCbBacaCCAAaaacBbBcaCACaaCAcbbcCCABcCBAACCaCABBcbaaaBBbcCABbacCBbCcbbBcabCaCCcCbcaCBaAcBCAbCabcCAccCaacBcBacAcCCAaBabBcBcCabbcCABBBcbacaAAcCcbCCCbbAcbBbbaCaaaaBCACCbBcbCAcCabaaCCaaabbAcAcaBCAAAabcACbBacBbbBCaAcacbaAAabBAbBbACCaCAcAbbbABAcbcBBabCcCabAbBBaacaBCcbaaAaaBcCCCBacbbbBBBcbACCaBCaaBccbCABBbcacaaCCAbcbBaACBcCACbACCcAAbcbACaaacaabbBAacBcAaBCabABaBaBaacCCABCcCbAcacBBccccaCcccaAbAABBcbCbbaBcBccAAaBbABAbBAAcAccBAbCAbCCAaaCACCaBabccbACcbBabACbacacAcbaaCCcbbBBaCacaCcABbacACcbbCcaCBCAabaCCCbabacbbaacAaaAcbbcccaABBaaAacCCaCCcbCCACABbCAaACCCBAcbBCBbBCAbAbcaBacbacbacbAAbaBccCAaCCCaABBbBCbCaaCBCcBcABCCbABBAbaBAAabcbAbCBCBbacBbcbCBaBCCCABBBbBCcbaAbaBcaaabbcAbaCBccaBbbcbAAccBAacaABbcaBBBcccaAcbCCBBBbbBbCBcCbAcCcAbAacaCcbcAAaBacbBCCAbbAaAbaaBbCcBCCcbACCaBabCbcaCBcABcBBaabcaCcCCACBaaaABCcCaBBcBbbBcBabAbBabcBCcBbbaBAAaCcBcaBaaCcABaCbcCAAcCabaCaAAAbacCaAbabaBaaCCCccBaaaAAabcbbCcbBaaABABACbaAAbacAAcBcacbCCCbABcBaAaCBBCCbCacBAbbCABCBAaCCCAbCcaAcbbccbAabCaabaaBbAbAbaAAAcCBABbaacABBcBAACaaAAcaAAABcACccaABCBBaABCbBABAbBaaAAbAaCcCCABABcBcbCBAAcaBcBccaBcAAcbCCAcbCabcaaaCbaACCcAbacCCabaBaAbBCabbbbcABcBCBBCcCccBbaBbACcCBaacBBACaBBaCabaBBCcCaaBCBcCAcABaBACaBbcAABbaBBACccbCAAaccBBbBABCbcAAbAcaACBBbcaabcbcCabcCcAcCAaCBCcAaBbBBCCAbcBBbcaBccBcaBABBBcabcACbbaCBCaacABcCaBabcBccabbABBCABbCAaAbbccBbCbbAbaCCbaAcBbbcaaCbBCaBaAbbAAcaCCcbAcBACCaBBbBbbBCaaacaBABcaBCbcaBBcCaBCcAaBbbBaAaCbBACccCBbcbBBcbabABbcAabbBaCcABbBCAAccCbAbcBACAcAbacBccbbAAbCCAcBAAacbbCBBABbAcbAbccCbBABCAAabcaABCCBCbbBCBCcBaCbAbbbBcAbAbacACCACbCacaCCbbcACcBbBaaAABCbbCbCcCaCCAcBcaCBAACcCACCCbCAABAbaaCcCbBBBCAAACbBAAaAAAaaCaaacBaaACBaabcBaaCaACcaBcCbaCcCcbCcBCbBbBBCacabcbAAcaACaCbcBAcaAaAaaAAabBAabAbCcCAAcbaCBBcAaBBCBCcAcCCAcBcbacbaaCBBBCcAcabaaCaBCaaAAACccCbbBAaBABaCACcCBABcCCAaAcAcBbbCbCABcBcBAAaCbACcCcAacaCaccBBCBbcaCacbCCCbAcCBBbBBbBacCacBBCcbBcaAaBbCbCCBaAACaCcBcAAcbAAcaCAAcbCcacccbAABCCBBcAabBABCBAbBAABAcBcAacacbABcABcBaaccCAaBaBBcAAABccBAbCAbbAaBAccCAabbCBAACaACBbabCbCcBCCcBBaCcBbCBAccbcbcbCbbABaCcabbBAccccaacAABacabccbaAcbAcAAABAcCcbAbCABCbcacBbcBbCAbACBbBCbAbBaCBcCBAcCbbCcBabCacBBaaaabcbcABabBaAacBbAbCCbbAbabacCbAabcbCBBabAaaCccabCBcCBaaABcCACcBCbbaaCbcabACbAAcBCcaCACbCcCAabacaaaCBbABAbcacaAbCbAAbABcCCcbbcacBBcccaaAAcAcAABacBbcCcAAAaBAAbCAABCCcBCbBcaCAbcbBBBbAbcaACcBbAbCACaCabCBCcBcCBCbBcbBaBcCbaCacaBcbCcAaacCabBAacBccaBbaccCcCaBaacBBbBaABBBbbbacCaABBCCBAAaaabaAAacccACCaCcBAACbAACbAACabaaCAbBBcCbaaBaaBAACBbCCCacabAbcCBabcCBAaCACcabccabCabaccAAcbccBCAAcaBaaBCbBacBABCBcaAaacCBAbAbABBAcAcCBAaBAcAcABcBcCBcaBBcbaAAaBCbBBaabacbbbcCCabBAaAACBaaCAbbCCbbabcCBBBABbBbbCAbBaAAAcCcCCaaAabccaCBCAaBCbCcAaaacCABbCaBaCBccbbCCbcaBAABbbaacAaAACBACAbCcBAbBccBCbbAcABAABabABbbBcABcaACacACbbcbBabaBABBCaccbCaabaAcAcBcBbbbbAbcCbcBAabbAbBcaABccBBBaCCaCaCAcaBCAAaBBcCBbBAacbCBbbCcaABACcbCbcABaBbbBCaAaBabcbCCccCCCaBcaCacabAaCbAAaCCBACAcBBbbCCcAbCAABbbCCCCAabCaaaaabbaccbBbaaACbaCcaCbBabBBaBAaaABbcCAABAbBCAacbBBBBBcAABaAaaBaaBACAbcCcacaCbABacbCbCAaBbcccccAaabBaCCABcBcAAbCaCbBBBaccbBcAACCaABbcbBccaBaCcCaBBbaCaAbcCCaCaCAaCcCabbBbabaAcaCbcabBAbbCBcCAcBBBbbabCcbCbCbBAcCaaCcbbCcbBcCbCCAABcaBBAabBAAaabAACcbBCABccacCAaBaCbCCcccBBbaCCBCbAbaCCaccACBbcbACCCcaAbAbcabbbABCaCbBCbbbbACBaAcBacaaBbbcaBacABabcccACabCACBcbCcCCbAaCBaAbcccacAbCcBbBBCaCAbABBacBbaAcbbCCACcABCBbCaBaaaABCcBBbaaCBBbBaBCBAaBAbBBbabCcBAbbbBaBccAAaCCcbACAbbaACCCbbCACbBAAbAAACcAAACCcCbcCAcBaCACbBbCBACBbCabaAcccACCACAbCAacacAAcBcAbbcBBACccCcBbCbBbbCAcCABBCAbcaAbBBabCBACaCCbacCBaAbAaAAbabbcacbcaCabcacbbcaCAbbbbcabbAAAacbAacCBaabbAbcCacacBcaAccCcCBAAbCaabCacAABacaCCacBBBCbBcCCbaCaACBcBCcBaCCabBCbaaCABCBbcAabACBABbbaAacCbCcaAbccaCCacAccccabbBbbcCaBbACbCacCACcccAaccABaaABbCbcBAbAbBcCacCaabbBaCAabACAcBbAbAbACBCcBcACaABbaBBcBABaccaaaCbcACaaBBbBBAcbaBCcbACACaCacbAAccBAaACcaCACcAcCAcbBCaBcCaaAbBaaBAbcAabcACCbCAcCCCcabaaABBABbacbAcBCaAbABaACCCCbcCBacabBbbbcCbaAbbBCacaACBcABbBcbbCCAccbCcCBcbbAAbacbbbccCaBAcaAABbCaaBabbaABBaBbBbCbbcaCaaCCaAcbbCBCBbAabBcaACBbbabcBaabbcBaCBCCcBBBAACbBbaBAAbCBaCAabbcBCCBbAABABabCCCaacACbCCAcBCaBcaBCcccCbBaCAACcacBbBcACbCBBaaAabbAAbcAcaCaccBaBACaAAbcaBacCcBcCCCBaAacaaccCAaCbbCACbBbBcCCABaacAaCbcbCcCCCaBbBCcAbcBAaBAacccaBBacAbCCaCBbcabbCCaCBbaAaAacBcCbbaabacCAbBaAACBcacaaaAACbcBBaAACAcBaacaAbCAbabbACCcABAbCcBBabCBCababAAabbbBAabCbbBAbaaccccAccCBABbabCbbcABcbcAcCcABacABAABCbACAccCCbcCcaaCaAaAACcbcBBCacaBccBCBCAcBaBbBbcbaaBBAbAaCBAaacaBccbCBBbCcCBAbcAcACBaCbbBcBAbaBbaccbCaCcbCBaBAcBccAbbBBCaBaCBBbCCCCcaabcccaBaCbCbCBbbAcAcBbABaCabCBccaBAAAAAbAAAbcAAacaccAccCbBBBacabCAaBCcABcBBcBcBcacacAacCAaAbAaACACCAAbaCAAAAaCBBABCACabCBaAbCAcCAcbBAbbcccCCcaBCbCcabcaABBACBCaaCAbCcbacaaBbBAaACBccAAcABBcBBCcaBcAcaBBbBBBbCCABbacCAaBbBBAaCbaaCcbcbaaCbAabcCcbcBBaBBcCCbaCccbBBCCCCCacBcAaaCacCbCcbACAbcCAbbcbbcbBcBbABaBBbAAcaCCAbAbaBccCAbBabCaACCbAAbaaBCAAAbaCBcBaBBCaBBCCcbBabcCcBaAcCbACBcaCacabbbacCCBaCCaCBBCaBbcBCacccCaACcaacbcaCbBACcBAaBABCBbccbbCABbababBBCAACCCabcacaBcaccacBCCaCACCCBCbcBBBACBBABbCCacCBccABACBCCcbaaaBbBaCbbccbcCaaccBCaaACBBccbAbCBAacbbCbAbAaAbaccACaCCcCaBCbaCAbAcABbAABACcAcCcCCBcBCaCCCAbCCBAbcCaaAcCcBBBACbbcCAbaBcaabaACcaaAbCbCcBAabaBcbCaBbcaAcbaaAaacCaacABaCCAACAaabbCCbbCCacCbCaCAaACbaCABBBccAcBBcCABbaBcabCBABabbACAbABBCCbbcbCBbBbAcAbCcaCCBAaCaBbaBaccAAbCCCbbbBbbAAcCABCaBbcaAaaaaaAacBAabCaBcAbcaBAcbBacAAaaacAbBccbCcBCaBbcbbacBcCCBaAcbCcaAaBabbbbcABcCcBaABCcAcbaABBcbcBcACAbCBCACCAcbbCbaAAcBabacBCBBCcCcaBCCBcBacbbbBACaaBaAAACbbaaABccCCCbABBabaCbbcBBbaccbBaCbbcBaaacCbCAcbCcbcAcBbAACabAbCAbcBABCAaacCBbcBAaABCbCCcacCBBabcACBbCcCBcaAAaAAbcbCAACbBcBcBccCAcCabBBcBaACACbaCcaBAccbcaBabcAaBaCCAcaCAcCAAAaACbAcBabbBBaaBBabBcBACbCBbbbBcaabCAcAbACBcbcccbCBBbaAAcBacbcbACbaAaCacAACBaaCCAAbbBBCccBABCcBcaAAcACcCaACcabAbbaAaBBACaaacBCabCcaCacaAACbACbaacccaAbacBBbAAbaAabCACaAaCBCaCbAcabbBBbabABBBbBaaAaacBCCCAACBaaaBabcCBBcBcaBBaccCBbaCcBaaaAbacBbacaaAaccaacCAbbbcBCABaaccaAcBbAACCccCBBBabccBAbcbAcBAbbCcaaaAbACACcbBABBAAbbBAcACbcaCbCaBBCcCbBAcCccCcCbaBcbCcCbbbaaabAbACbbcBaccACBbaBAbaBbCCccACaABCcAbBCbACBAcBcBaAaAcaaBBcacBBaACBAaBCcacCbAAbCbbcAbBAabCCcBaBACAbaBCCBBCCccaCacbCcCCCCacaabbcBbcbAbBCbcCBCBbCcaBACcAbAAabbAbBaCcbBCcAaCCAAAaaCbaaBbbacbABbBBcBbCbAAAaCbCBCabcCBbabCbbCcaCbccCACbCBccbAabaBcABCcBAcAbbabBbaacbaCCAbCacCCcbbaaaBaABbbACABcBcCCcbaCaAbAAbAaBbbCBAaABCcacBcCBCbACbBCaaBBBAABBbBBAcaaaACCCAAACcccBaabCbBacAAbaAcCBbaABAAABcccAbCAbAaCabBAcbcAAcAACAaaaaBBABbaCcaCcAAbaaCBCbCCcACACacabBCaaCBbaCBBBbaccACCcaCcBBCcbAaaAABBCBACCbccAbBbCCCcBBAbBbbbCBCAcBCAbcbBABACaaABcbcCcAbbBCaacccBcACbCabCBABAcaaBcBaaCCBbbCBcBcBcBCBaCcACcAaccbBAacabBabbCAaBBaAAaBCCBBbccaBCCcbaabCCBCCbAacaBbbAAAcCbABCCcBbbcABBAaCBacCCBcbaACbAbaCcbCcccAaAabCAabAbaACccBbBBCCbBabBAcAbabcAaccAcCCcbBAABcCcCAaccbcbbAcCbCcAAaAcCbbCCcBCCCbBBBCBcBACaAABaaabbBccbcaBbaaaaaCCCBCACbaCcbbABBaaAaccBBAACCcCBacCbAcCBCBAaCCCCBbacbCACaccBBcAAaBAAcABaAaBBBcCcbCAaaACacccaCaBabaabAcAACcAcaaAAccABAbCAaaBBAcBcccBbbccCaccbaaCACCaCcbbCBbBcbAbbbaBCCCBBBcacaACaCaBcAaCcbabbcaaAcbbBacbaacCacbbBBACCAbACaCaacAAAAcbAcBbBABbaBAacbaccCcaCBCbbCbCaCCbAacCcacCccBAcCAbbabBcaaABBCAbCBBbabCcBcbacABBcBaCbcBbbCBabBACACACCaaaBcCbCAbBacACACBaCCbCaabBcaaacaCCCacaAAAbACcccCCaBCCcbBaCcabCaCCAccAAbbaBaCcCAbBBccacCaACaabBbBbAAbCbAcBaAcBCACBbBcAabBbACbbBaAcAbAbCAaacABcBbccbBCaAcacbCAAaCbCaaaBaAaccbBcbaCaCBbcbBaaACbbCCaaCCBaaCCaAaCACCcAbaccaCCBBabbcaABBBBCACaabbCBcbbAaaACBcCCaaBCBAAAaAacAAbcbbBABBbAAbBbAbaBcaCBAaCBaBaBBAABAcaabbBacBCbbaaAaCaacCaaaCBAaaabCCcaAaBAaCbCabBCbCCcbcacbAcBbbBAAcBcCbBCBbaBCCcbCABcbbCAcbBbbAaacaacccAcAcCBccbbbCbbCCBBCAbABbbBbBccBAAcbcaaBAaAbccCcCBBcBCBbcBcACBAAAcaCCbCcAAaAbbaACcCccACCcAabbaaBBaCaABbbcacaAbbccaaAaaBcaaBcccaBCccCACAaAaCBCBbbCABCbBcaccCCcaaacBBAcbBccCaACCAbcAbCcCcCAbcBaaacbaBbaACcCBBAcaabcbBAbbaBcCbbBBcaAccBaaaaCCAacbCbbbABaBbcBcBAAcBacAbCbaabCacbBABCBCcbbaBCAACbaAcabbbcbBaBbaAAcaAccAbABcbBbbCCcABBAcCBBCbccBbAAbACBCBCAcBaaaccabBbbCcbBaaCBbcCBABccccABcaCBbBaaAbbcAcAcbccBCaCBbCCacAAbCaacBCCAaCBacABaaAbcCaCcCCaBcBAcaBabbbacAAACACBcBcCBBBaBbbabbACaAaabCAcCCcBCbbbaaBBBACbCCcABaCAcaaccAcacbcCCbbcababBaAAaCaAAcAcaCbbCbccAcCcBBcaCaabACCbCacccCcCcBBBABbAbBCaCBBBCAAABAaCCcaAaBcBcbaCcAAaaaCAabbAbbBbBACabcABBCBCCACACccaAbaaabAbcBabcacBCabBbAaAccbbcaababcaBBabBcBbbcccCabCcbbCaAcACaabbAabcCBBcbCaAcCAABbACCccaAAbcACbCCaCaCbaBbbacCcBBbCaCAbCaaBACAcCaCcbBacBabAcCabAACcBBAcaCACBABbbbAAAaaaBabCabCCbcaAaacBbBBBbBBcCbCAAcccACcbAbABaAbbCaCBaaBAACACbABbbBCbBAcbaBbcBABBcAACCCacCBAbcbCCBBabcbbBBaBacbACbcABACaBbAacBAaCbACBaBcabAcbBcbaCBaCbBBbaccACcAbabcacaBbAbBbcbCBaBaCbBcabcbbaCaBABcbabbabbcBcBbaaAcCCBBAbBCCCcbAcBcBBcAACCAaBcCAbCcCCaCcaaCabbAAbaaCaCACbCAbbaccbacCaBaCbcabBBAbcccAcBAbBCbBCBcABACAAabbbbAccBCaBacbcbaAbcAaBCcbccCacCccCaAbcBcBBcAbcACaBcBBCbcbCcbaaBAcaacAaaaBcbaCaaCBBCAaaAaca";
    var part3NotesExpanded = part3Notes + part3Notes + part3Notes;
    var notesArr = part3Notes.toCharArray();
    long part3Results = 0;
    while (repeat > 0) {
      for (int i = 0; i < notesArr.length; i++) {
        char c = notesArr[i];
        if (Character.isLowerCase(c)) {
          int i_offset = i + part3Notes.length();
          String left = StringUtils.substring(part3NotesExpanded, i_offset - range, i_offset);
          if (repeat == 1000) {
            // First iteration
            left = StringUtils.substring(part3Notes, Math.max(i - range, 0), i);
          }
          part3Results += calculatePart3NoviceMentorPairByChar(left, c);
          String right =
              StringUtils.substring(part3NotesExpanded, i_offset + 1, i_offset + range + 1);
          if (repeat == 1) {
            // Last iteration
            right = StringUtils.substring(part3Notes, i + 1,
                Math.min(i + range + 1, part3Notes.length()));
          }
          part3Results += calculatePart3NoviceMentorPairByChar(right, c);
          // LOGGER.debug("part3 test: {} {} {} {}", part3Results,
          // calculatePart3NoviceMentorPairByChar(left, c)
          // + calculatePart3NoviceMentorPairByChar(right, c),
          // left, right);
        }
      }
      repeat--;
    }
    // Not the best algorithm (works for the actual puzzle notes, but failed on the sample note of
    // range 1000 and repeat 1000 (because sample note is too short)
    // Made the assumption that 'range' will always be within 'notes' x 3
    LOGGER.debug("part3: {}", part3Results);
  }

  private static int calculatePart1NoviceMentorPairByChar(String input, char type) {
    input = input.chars().filter(c -> Character.toLowerCase((char) c) == type)
        .mapToObj(c -> String.valueOf((char) c)).collect(Collectors.joining());
    int results = 0;
    int mentorCount = 0;
    for (var c : input.toCharArray()) {
      if (c == Character.toUpperCase(type)) {
        // Mentor
        mentorCount++;
      } else if (c == Character.toLowerCase(type)) {
        results += mentorCount;
      }
    }
    return results;
  }

  private static int calculatePart3NoviceMentorPairByChar(String input, char type) {
    int results = 0;
    for (var c : input.toCharArray()) {
      if (c == Character.toUpperCase(type)) {
        results++;
      }
    }
    return results;
  }
}
